---
ID: "4d506879-e162-44d3-b314-b8ffa154062a"
Parent: "e40f3dd8-44fd-41b7-b99a-623179f4e684"
Template: "e40f3dd8-44fd-41b7-b99a-623179f4e684"
Path: /sitecore/templates/SF/Feature/Social/Interface Templates/_SiteGooglePlusSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170703T025546Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
