---
ID: "dfd1b892-04d6-4ef8-9686-749786e4a839"
Parent: "9bcbd489-f864-4f8d-89d8-012bfb7841a3"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/SF/Project/Common/Content Branches/Site
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150509T213407
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
