---
ID: "f20359ec-7391-4289-a085-e460e4eaae87"
Parent: "2e4e13e8-697e-4e3a-b9ee-117dd514fbff"
Template: "48f508b1-de5c-4cfd-acf1-1fecf6af8f34"
Path: /sitecore/system/Data Exchange/Foundation Database Tenant/Endpoints/Providers/Database
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161115T023647Z
