---
ID: "68916236-a4bc-4099-aa7b-065490dd6e95"
Parent: "28a789a5-c78c-4b51-9637-8c6c2e6fdf80"
Template: "28a789a5-c78c-4b51-9637-8c6c2e6fdf80"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/GridParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T001921
