---
ID: "04be8c48-321a-4ec4-8284-5f0d129df19b"
Parent: "a02bd404-6169-46ed-8226-41bef6c04e8b"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/SF/Composite/Rendering Parameters/Composite Component Rendering Parameters/Composite Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171020T000355Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
