---
ID: "446a6f3c-0a58-404c-88c8-d212bf2f8b23"
Parent: "fecb92c7-27c7-4376-946e-1983853cb276"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/SF/Feature/Database/Pipeline Steps/Audit Dictionary Pipeline Step/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170428T190915Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
