---
ID: "c95201dc-84fa-4bb2-9abf-372645056007"
Parent: "0c3b4704-a0c1-4010-8fae-fceed680f329"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/SF/Feature/MetaTags/Interface Templates/_PageMetaTagSettings/Meta Tag Details/DisableGlobalSettings
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Checkbox
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Disable Global Prefixes and Suffixes
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140911T112453
