---
ID: "185813d4-12d6-460d-9bc6-f7acedddc925"
Parent: "1f06bef9-bd5e-44d4-bb1f-b7d08ebbdf57"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Feature/Redirection/Rule Templates/Redirect Url/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150731T095303
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
