---
ID: "233b36f2-1b0c-4252-a7a6-69e4713648d6"
Parent: "d95aeb3f-3817-4d07-bb87-f139eda70d6e"
Template: "d95aeb3f-3817-4d07-bb87-f139eda70d6e"
Path: /sitecore/templates/Data Exchange/Providers/SF/Feature/SitecoreProvider/Data Access/Static Value Accessor Set/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{C559AA17-221A-4374-A6B6-58B5DDE38364}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170126T211307Z
