---
ID: "e5f964a5-becf-44ba-a5f6-3d45cb3a9430"
Parent: "fb373191-3fc9-4bb4-8010-ae91eedeaf9e"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Site Configuration/App Settings
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {A87A00B1-E6DB-45AB-8B54-636FEC3B5523}
    {2D8DCE92-5BDE-48C6-A17A-6669D8DF0461}
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170502T180632Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
