---
ID: "a25274bd-aaee-4aee-bc22-d3b8fbc0298a"
Parent: "ff589e18-8339-4fbc-93e9-732bdcce88bc"
Template: "1c7cbb97-485d-4540-9d41-f3a3f90ed85c"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Home/Playground/Handlebars/Content/HandlebarDataSources/Products Collection
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151113T145604
    - ID: "5db357fa-0dba-4347-b70b-5eb20ae353f6"
      Hint: Items Per Page
      Value: 2
    - ID: "6ccd6589-ef6b-4e8e-844e-e1819c15d9ba"
      Hint: Root Folder
      Value: "{ED634505-683A-4A3A-80D4-F7669375D570}"
