---
ID: "85b3f746-915f-4f7f-9a87-02e126b48822"
Parent: "584955f8-5b31-4d73-b012-6e1c54aec43b"
Template: "584955f8-5b31-4d73-b012-6e1c54aec43b"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Component Templates/IconBarItem/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150912T233210
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
