---
ID: "c950f9ec-86a4-4f37-9de6-c2c292dc9319"
Parent: "de9b0c94-2505-4ce5-b4d1-f02d15c676b0"
Template: "ea8a3f26-9ccd-443a-95f5-71b868a94bd0"
Path: /sitecore/system/Settings/Foundation/SF/Configuration/Configuration Site Setup/Add Site Settings Root
DB: master
SharedFields:
- ID: "4795a7c6-08a9-4248-86c3-d460062c3a22"
  Hint: Location
  Type: Treelist
  Value: "{6A8A971B-01BC-4749-9EF5-10C69BBA73FE}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Site Settings
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{4ABA36D7-A67F-4A1E-8866-67A42B6FEC00}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180203T230145Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
