---
ID: "c5b81228-c6aa-47aa-a4bc-36ab21c5edf1"
Parent: "3fb548a7-430c-4baf-888e-22c8c430c1a3"
Template: "3fb548a7-430c-4baf-888e-22c8c430c1a3"
Path: /sitecore/templates/SF/Feature/Social/Interface Templates/_SiteTwitterSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170703T025553Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
