---
ID: "60289c93-53c4-40fe-bced-27feb1cccd59"
Parent: "50906b57-846c-4e3c-acc6-f0a03faa32b8"
Template: "713398d7-366f-4122-a7c0-8bc9ac235df7"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Home/Features/Tags/Content/Images/Page Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151006T222636
    - ID: "3f587316-405d-4e2e-90af-dfef50b981ca"
      Hint: Caption
      Value: "Page Level - Meta Settings"
    - ID: "549ab079-3a2d-4099-a79f-4d4b6342e69d"
      Hint: Image
      Value: |
        <image mediaid="{5B89BE25-D854-422E-823B-C30536BEBCC5}" />
