---
ID: "5fa39f50-0999-4390-8c54-ea4fdc3089c4"
Parent: "50906b57-846c-4e3c-acc6-f0a03faa32b8"
Template: "713398d7-366f-4122-a7c0-8bc9ac235df7"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Home/Features/Tags/Content/Images/Site Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151006T222746
    - ID: "3f587316-405d-4e2e-90af-dfef50b981ca"
      Hint: Caption
      Value: Site Level Meta Tag Defaults
    - ID: "549ab079-3a2d-4099-a79f-4d4b6342e69d"
      Hint: Image
      Value: |
        <image mediaid="{5CE8A97F-79FC-4383-9981-8DA74E6A7EA8}" />
