---
ID: "1c7f32d2-1209-4abc-ace0-8d0ddee0c543"
Parent: "702a57b2-ffa9-41d8-966e-b423bb4f8596"
Template: "702a57b2-ffa9-41d8-966e-b423bb4f8596"
Path: /sitecore/templates/Data Exchange/Providers/SF/Feature/General/Pipeline Steps/Iterate Through Grouped Data/__Standard Values
DB: master
SharedFields:
- ID: "3c7f78cc-0c5c-4076-80ef-9a49fda5ff96"
  Hint: ConverterType
  Value: SF.Feature.DEF.General.IterateThroughGroupedDataStepConverter, SF.Feature.DEF.General
- ID: "a83a2eb2-bfa1-4d3f-9f17-0cc6c9a91c42"
  Hint: ProcessorType
  Value: SF.Feature.DEF.General.IterateThroughGroupedDataStepProcessor, SF.Feature.DEF.General
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170830T183832Z
