---
ID: "84cea7de-dea7-4785-9120-6538a2c6088d"
Parent: "702a57b2-ffa9-41d8-966e-b423bb4f8596"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/SF/Feature/General/Pipeline Steps/Iterate Through Grouped Data/Grouped Data Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171025T233354Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
