---
ID: "de9b0c94-2505-4ce5-b4d1-f02d15c676b0"
Parent: "4443e606-a9bd-4682-8ffd-8482cc78f230"
Template: "292ccfcd-7790-4692-856b-76014b8038e7"
Path: /sitecore/system/Settings/Foundation/SF/Configuration/Configuration Site Setup
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180127T162224Z
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Configuration
