---
ID: "3b6f2df9-3889-4f4a-a2f2-02ee3e5d720a"
Parent: "d4adf31c-f2fc-45c6-84aa-13d0c9b31973"
Template: "a050492f-bdba-4f31-8fc7-48aad1eda0a5"
Path: /sitecore/content/Global/Shared Content/LogoutSettings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160125T224058
