---
ID: "a310420b-e3f6-435e-9627-b3da39abc849"
Parent: "4b31eb5b-5bb9-4f2c-8190-b75b9a44f6f2"
Template: "4b31eb5b-5bb9-4f2c-8190-b75b9a44f6f2"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/OffCanvasParameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T232405
    - ID: "6e0d8a48-0aac-4366-b53f-e7c3ad49a0e5"
      Hint: TitleAlignment
      Value: middle
    - ID: "d082b79a-c4dd-4c02-b7ee-04c86589804d"
      Hint: MenuIcon
      Value: "menu-icon"
