---
ID: "0bf3ef15-372e-42be-9c7c-42c18e502228"
Parent: "4b7a43cc-afc5-4834-bb29-39d197f28afe"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Feature/Redirection/Interface Templates/_SiteRedirectionSettings/Redirection Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 750
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150820T105223
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
