---
ID: "2707cb91-17b7-4beb-a34f-fe1ab869c342"
Parent: "91b35341-1d27-493e-bc7a-a92032efe6cb"
Template: "91b35341-1d27-493e-bc7a-a92032efe6cb"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/LabelParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T001921
