---
ID: "e915d3fe-71d6-46f8-acd8-524aafb7bb47"
Parent: "489e0fa3-1980-46e0-b0bc-09e2e73be27c"
Template: "489e0fa3-1980-46e0-b0bc-09e2e73be27c"
Path: /sitecore/templates/SF/Feature/BlogSample/Content Templates/Category/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160726T134505
    - ID: "3c313955-2c54-4017-a610-1d24bf747570"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
