---
ID: "5e1040d4-e7b3-47c0-b35b-18f869bcdb10"
Parent: "c2c869f2-c7d2-44ca-9992-82d91e41cd21"
Template: "c2c869f2-c7d2-44ca-9992-82d91e41cd21"
Path: /sitecore/templates/SF/Feature/Social/Interface Templates/_PageSocialSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170703T025653Z
