---
ID: "3e2a3a73-6c1c-46e2-8454-4901af1bdbfc"
Parent: "22befd7e-45e7-4dbc-b529-85e72d01be57"
Template: "22befd7e-45e7-4dbc-b529-85e72d01be57"
Path: /sitecore/templates/SF/Feature/Handlebars/Component Templates/HandelbarFacetContainer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160914T200956Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
