---
ID: "36b47b76-9bc4-4b6e-bd3f-38b4bb11d1df"
Parent: "5b2c7897-a053-4b7f-a3d7-baf516fba747"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Feature/IPWhiteList/Configuration Templates/IP Range/IP Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150805T223400
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
