---
ID: "cca079ff-f6e3-4ffa-aaf1-7220ec8d3892"
Parent: "8aeafc65-5b1e-4eb0-89a0-20018400ed3f"
Template: "a53e7d14-49e1-4271-af55-47f65aeec5ca"
Path: /sitecore/content/Starter Kit Sites/Shared Content/LogoutSettings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160125T224058
