---
ID: "7220c8e3-9916-42b0-9225-18269af97ec1"
Parent: "6694869e-72f2-408f-9848-90a23c45ece7"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Feature/MetaTags/Interface Templates/_SiteMetaTagSettings/Meta Tag Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140911T112259
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
