---
ID: "106567dd-f956-4744-900a-ba751f7db0ec"
Parent: "60fd422f-0637-41ac-af87-dc78affb4927"
Template: "a280aab8-15a0-4646-9d39-c606e81be744"
Path: "/sitecore/content/Global/Pick Lists/Airspace Service Icons/ion-ios-compose-outline"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170801T122022Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
