---
ID: "89aa5c9c-f0ea-43cf-8bc4-9332e8c510b0"
Parent: "fc17f53e-e146-485b-9d1e-d192f5694577"
Template: "b0c4da22-e26f-472a-9fe9-7a5030684a14"
Path: /sitecore/system/Data Exchange/Foundation Contact Import Tenant/Tenant Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170124T214438Z
