---
ID: "1f4c53af-ecf9-4fb2-9f12-aa0de38c4b01"
Parent: "e9e58626-9278-47b2-89d4-343e657f6c88"
Template: "80411d8d-9533-4912-97e5-3790fc4387d5"
Path: /sitecore/system/Data Exchange/Foundation Database Tenant/Data Access/Value Accessor Sets/Providers/Database
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161115T023731Z
