---
ID: "7c5a1ed8-2265-484c-8da2-f9f35980c412"
Parent: "e89c3408-6bc2-4c95-a395-7fe1ae6e4078"
Template: "e89c3408-6bc2-4c95-a395-7fe1ae6e4078"
Path: /sitecore/templates/SF/Foundation/Resources/Resource Types/_Resource/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151104T152532
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
