---
ID: "54851a84-5a99-4439-998d-e9a60ad42536"
Parent: "ea54f65f-a8a9-4d72-8344-393143a72535"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/ButtonGroupParameters/Button Group Details/Stack
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Checkbox
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150525T212340
