---
ID: "1a27afb5-3b01-4efe-a4a2-87a0b797ad04"
Parent: "2a2c02c1-a2b6-4c20-83a9-e23096e6bd21"
Template: "2a2c02c1-a2b6-4c20-83a9-e23096e6bd21"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Component Templates/ModalComponent/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150922T203141
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
