---
ID: "edaa2330-45e0-4f75-90c9-a2e47091eb4c"
Parent: "7a70017e-bb19-4d4f-87cf-47b31ae8da96"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/SF/Feature/Excel/Endpoints/Excel Endpoint/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161114T011948Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
