---
ID: "cb191e6f-775d-4a02-a1fd-02fc83dcb51e"
Parent: "f3c21ebe-b9f9-4b9b-8fe1-74c3687106b3"
Template: "f3c21ebe-b9f9-4b9b-8fe1-74c3687106b3"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/BlockGridParameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150510T204800
    - ID: "a4835ec7-74a0-4645-b97f-0af85ea823fa"
      Hint: Small
      Value: 3
