---
ID: "e5cc1cbb-fb29-40af-b5a5-15c4d462edf8"
Parent: "5dd10fe3-d574-43e9-87b2-363b869ecba9"
Template: "5dd10fe3-d574-43e9-87b2-363b869ecba9"
Path: /sitecore/templates/SF/Feature/BlogSample/Content Templates/Author/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160725T103458
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
