---
ID: "fb373191-3fc9-4bb4-8010-ae91eedeaf9e"
Parent: "89f15d6d-e762-4695-9383-6bcac42f569d"
Template: "5b9f4583-bbd8-4b70-a45d-cc752a4fede8"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Site Configuration
DB: master
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0abf82c0-ab34-4745-a4d5-6ebfcea06731"
      Hint: Take Site Offline
      Type: Checkbox
      Value: 0
    - ID: "0c77a26c-1c00-427f-aa18-bcf83df753e6"
      Hint: TitlePrefix
      Value: Sitecore Foundation
    - ID: "144e332d-f429-429e-ab18-4b6d05b2180a"
      Hint: LayoutNotFoundPage
      Value: "{AAF0CD52-D558-4CDD-B999-F90F7F4DD353}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150603T181423Z
    - ID: "36d038d3-4e99-4482-9827-c3df2a679d46"
      Hint: Header
      Value: |
        <link rel="stylesheet" media="all" href="//fonts.googleapis.com/css?family=Lato:400,900,400italic,900italic|Roboto+Slab:400,700">
        <script src="/content/vendor/modernizr.min.js"></script>
    - ID: "4424082a-c9f6-469a-8363-c4d95b58f1d2"
      Hint: SiteScripts
      Type: Treelist
      Value: 
    - ID: "628d81e5-53c2-4da5-ae2d-0e9785af6eb2"
      Hint: Site Offline Page
      Value: "{C3E03478-5ED6-475D-B13E-A3A8BEABA83A}"
    - ID: "6e10df11-0de5-491f-8938-c162ae532278"
      Hint: Valid Languages
      Type: Multilist
      Value: |
        {AF584191-45C9-4201-8740-5409F4CF8BDD}
        {CF5DEA0E-8557-4694-8B4F-6548627581DB}
        {F9564DA2-E9C6-44DA-B63E-D2F3247ACE1F}
        {26F20063-0099-464F-9F84-936CFB825204}
    - ID: "7fb1a8d2-0773-449e-bbf3-1b33e4845ee8"
      Hint: White Listing Enabled
      Type: Checkbox
      Value: 0
    - ID: "82984827-4cfe-45a2-8d05-c063ca0d0047"
      Hint: RobotsId
      Value: "{08FF82CA-1BF9-4AE7-9C0E-32359E50FA94}"
    - ID: "89f9196f-3581-4575-9c2a-042f513f9412"
      Hint: BaseCanoncialUrl
      Value: "http://starterkit.dev.local"
    - ID: "9fda9f8b-f1e8-487e-85a3-bdbcbef16a6a"
      Hint: SiteCSS
      Type: Treelist
      Value: 
    - ID: "a70592c5-786f-46b8-98de-b560709bb81c"
      Hint: Force WWW
      Type: Checkbox
      Value: 0
    - ID: "bba037a1-1a20-4470-808c-a672078d1560"
      Hint: MetaDescPrefix
      Value: Sitecore Foundation
    - ID: "cec4ebae-c6eb-4b70-afe6-50677e8579d7"
      Hint: Force Https
      Type: Checkbox
      Value: 0
    - ID: "d2e3925b-2913-477f-bdee-22c7dc2fb178"
      Hint: Apply Rules For All Requests
      Type: Checkbox
      Value: 0
    - ID: "d46f9367-ed25-47af-819a-5a21ff68dd73"
      Hint: SitemapRootId
      Value: "{71B87E08-09C7-4E7D-8A0A-07F2FD2BFF24}"
    - ID: "d5e2ae75-9bbb-4e26-bdf2-fd3934e921ba"
      Hint: Minify
      Type: Checkbox
      Value: 1
    - ID: "e96c5095-30fe-4a9c-ae09-4767b9310927"
      Hint: ItemNotFoundPage
      Value: "{AAF0CD52-D558-4CDD-B999-F90F7F4DD353}"
