---
ID: "eac3d98c-4c1a-4ec5-8687-b129aaac826b"
Parent: "c7152672-0de1-4d57-a128-95c2b4ac43ce"
Template: "ecba4d31-ac46-4503-b327-03005b8c947f"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Home/Playground/Content/Templates/Product Template
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151112T234731
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c21ff5a7-06c2-4c71-81a4-6a5e84855047"
      Hint: Content
      Value: |
        <div>
        Product: {{ Title }}
        </div>
        <div>
        Description: {{{ Description }}}
        </div>
        <div>
        Price: {{ Price }}
        </div>
        {{{ ProductImage }}}
