---
ID: "c5e29e41-7966-47b5-860d-e85d86f82a60"
Parent: "182ca25c-5b31-45a4-9424-03b98c0594b4"
Template: "182ca25c-5b31-45a4-9424-03b98c0594b4"
Path: /sitecore/templates/SF/Feature/Favicon/Interface Templates/_SiteFaviconSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170702T003549Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
