---
ID: "decc887e-2b12-4f01-94fa-51d4ad1b7e69"
Parent: "182ca25c-5b31-45a4-9424-03b98c0594b4"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Feature/Favicon/Interface Templates/_SiteFaviconSettings/Multi Site Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140911T112300
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
