---
ID: "baf53d33-eced-4172-b8b1-3ce7465cec32"
Parent: "be97c7cf-f4ff-46b3-a197-279c534f8801"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/SF/Feature/SitecoreProvider/Pipeline Steps/Publish Content Items Pipeline Step/Publish Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170531T180916Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
