---
ID: "9986b0a4-cbfa-4918-8fe3-c26c0bf261a5"
Parent: "72fc6386-397e-4aa0-bf82-1f33b6db2b3b"
Template: "2964a997-65a9-4aa5-9b72-b78a88e03c74"
Path: /sitecore/system/Data Exchange/Foundation Contact Import Tenant/Data Access/Value Accessor Sets/Providers/Static Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170126T212811Z
