---
ID: "53d34504-8325-4e40-8d31-9f21175b026f"
Parent: "e34926aa-7eae-42c5-9a26-b078208d0a66"
Template: "e34926aa-7eae-42c5-9a26-b078208d0a66"
Path: /sitecore/templates/SF/Feature/BlogSample/Content Templates/Comment/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160725T102313
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "64ee5da4-85fe-4208-a708-6a3614077e16"
      Hint: Date
      Value: $date
