---
ID: "432a7f01-9cdd-452d-b710-18455ee39c0d"
Parent: "b7a94ed3-ef81-4465-9138-6fb30999f5c7"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Feature/Redirection/Rule Templates/Redirect Pattern/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150731T095435
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
