---
ID: "63b1b35c-b8ef-43fe-9718-9570996a5539"
Parent: "83c50b62-e947-460b-addf-d46ad92a5a1e"
Template: "713398d7-366f-4122-a7c0-8bc9ac235df7"
Path: /sitecore/content/Starter Kit Sites/Sites/Starter Kit/Home/Features/SEO/Content/Images/Page Site Map Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151009T014151Z
    - ID: "3f587316-405d-4e2e-90af-dfef50b981ca"
      Hint: Caption
      Value: Global Site Map Settings
    - ID: "549ab079-3a2d-4099-a79f-4d4b6342e69d"
      Hint: Image
      Value: |
        <image mediaid="{6D57ADCB-82B0-497A-9F5B-0D3199040ADE}" ></image>
