---
ID: "30224dce-97d6-4ea3-92a5-e87ca89fd19f"
Parent: "83c50b62-e947-460b-addf-d46ad92a5a1e"
Template: "713398d7-366f-4122-a7c0-8bc9ac235df7"
Path: "/sitecore/content/Starter Kit Sites/Sites/Starter Kit/Home/Features/SEO/Content/Images/Page Site Map Settings - Really"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151009T014424Z
    - ID: "3f587316-405d-4e2e-90af-dfef50b981ca"
      Hint: Caption
      Value: Page Site Map Settings
    - ID: "549ab079-3a2d-4099-a79f-4d4b6342e69d"
      Hint: Image
      Value: |
        <image mediaid="{E298F427-3790-4E0A-AF1A-3E2D5405B543}" ></image>
