---
ID: "34f25f55-820b-45ab-bf31-233548770075"
Parent: "4d3259cc-6610-4447-9fba-f65366c22e24"
Template: "4d3259cc-6610-4447-9fba-f65366c22e24"
Path: /sitecore/templates/SF/Feature/Social/Interface Templates/_SiteFacebookSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170703T025159Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
