---
ID: "77dc4e56-17d9-494a-a857-bd57883c57f3"
Parent: "8b5ee303-4cca-4f87-a9a1-6da83cdbdd2d"
Template: "8b5ee303-4cca-4f87-a9a1-6da83cdbdd2d"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/ButtonGroupParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T001921
