---
ID: "89a63e66-fc57-4a71-a0bb-3bb2860db6f7"
Parent: "54e37166-a3a1-4bed-bfcb-3ae7d3c7ec06"
Template: "54e37166-a3a1-4bed-bfcb-3ae7d3c7ec06"
Path: /sitecore/templates/SF/Project/StarterKit/Content Types/News Items/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160529T030224Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "915fa630-9ad7-44ac-bcde-9865dc8789e6"
      Hint: Title
      Value: $name
