---
ID: "5f65ce2f-e3e1-4929-ba81-12e180384e22"
Parent: "7bd0b0ec-bd97-44b1-91c6-dcb0f52942c7"
Template: "7bd0b0ec-bd97-44b1-91c6-dcb0f52942c7"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/ButtonParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T001921
