---
ID: "724e585b-ea32-4a6e-b0e2-85a39c8839f7"
Parent: "491f15f0-661d-4073-ad4b-6ea0f2ca644a"
Template: "ea8a3f26-9ccd-443a-95f5-71b868a94bd0"
Path: /sitecore/system/Settings/Feature/SF/IP White List/IP White List Site Setup/Add White Listing Settings
DB: master
SharedFields:
- ID: "4795a7c6-08a9-4248-86c3-d460062c3a22"
  Hint: Location
  Type: Treelist
  Value: "{6A8A971B-01BC-4749-9EF5-10C69BBA73FE}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: White List Settings
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{3C1715FE-6A13-4FCF-845F-DE308BA9741D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180203T183710Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
